### ISSUE TITLE
sentence length and padding

### ISSUE THREAD

**Issue by attardi** [yoonkim/CNN_sentence#9]
Why do you pad all sentences to the same length, currently fixed to 56?
Shouldn't padding depend on filter size?
Right now it is fixed at 5 in the call to
   make_idx_data_cv(revs, word_idx_map, i, max_l=56, k=300, filter_h=5)
BTW: k is not used.

**Comment by yoonkim** [comment]
it's because we do SGD with mini-batches, and each mini-batch has sentences of varying lengths. one could sort/group the batches based on sentence length and then there would be no need to pad (as is often done in NMT).

**Comment by stephenhky** [comment]
A carry-on question: if the sentence length allowed _n_ is greater than the real length of a sentence, what would the vector be for the remaining vectors? Are they set to zero? Or given random values to the vector elements?

**Comment by HYY0508** [comment]
Traceback (most recent call last):
  File "conv_net_sentence.py", line 311, in <module>
    datasets = make_idx_data_cv(revs, word_idx_map, i, max_l=56,k=300, filter_h=5)
  File "conv_net_sentence.py", line 283, in make_idx_data_cv
    train = np.array(train,dtype="int")
ValueError: setting an array element with a sequence.
follow your code,I meet a quesion,Is that the same reason you're talking about?

**Comment by moses9591** [comment]
You should change this line train = np.array(train,dtype="int") as following:
train = np.array(train,dtype="object")
